spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:5456/wise_gateway_db
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update